name: Start Infrastructure

on:
  schedule:
    - cron: "40 4 * * *"  # 10:10 AM IST (4:40 AM UTC)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  start-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::855386719823:role/github-infra-control-role
          aws-region: ap-south-1

      - name: Start EC2 instance (User)
        run: |
          aws ec2 start-instances \
            --instance-ids i-03acbabc3588912c6
      
      - name: Start EC2 instance (Admin)
        run: |
          aws ec2 start-instances \
            --instance-ids i-0c41ce2766d8fe0b5 || true

      - name: Start RDS instance
        run: |
          aws rds start-db-instance \
            --db-instance-identifier reportmitra-mysql